### ISSUE TITLE
How to user personal package in the config?

### ISSUE THREAD

**Issue by ztlevi** [hlissner/dotfiles#12]
Hi,

I'm trying to add some packages that haven't been added to nixpkgs. But I couldn't figure out the way to use the defined packages in the config.

Basically, I create a new `stdenv.mkDerivation` under `./pakcages/<new-package>.nix`. But when I try to use that package in the config, it couldn't find it.

How to add personal packages in the config?

**Comment by hlissner** [comment]
[This line](https://github.com/hlissner/dotfiles/blob/master/flake.nix#L51) puts it under `pkgs.my.*`. So `pkgs.my.new-package` should hold the package you're looking for.

**Comment by ztlevi** [comment]
Ah, nice, it works!

Is there any recommended source that teaches ppl how to debug personal nix build? So far, I only find things like `builtins.trace` and `lib.traceSeq`, and they are little hard to use because we have to put them in a `=` statement. 

Otherwise, it will raise error like this
![image](https://user-images.githubusercontent.com/16655096/101994000-cc371680-3c73-11eb-9315-c69a9ad6c113.png)


![image](https://user-images.githubusercontent.com/16655096/101993949-6185db00-3c73-11eb-8d01-7a980a5b9469.png)
