### ISSUE TITLE
How are you managing doom-emacs?

### ISSUE THREAD

**Issue by tim-hilt** [hlissner/dotfiles#20]
I found a commented out section in `modules/editors/emacs.nix`, which seems like pulling in doom, if the `doom`-flag is enabled.

However, if that is the way you typically install it, why is it commented out? Are you managing doom outside of the NixOS-config or something?

Not really an issue, but I think that it's an interesting question that I haven't really found an answer for yet.

**Comment by hlissner** [comment]
Hi! Sorry for the (tremendously) late response. I manage Doom by hand. The commented out block is more than fine for Doom users, who won't touch `~/.emacs.d` much, but being it's author the directory sees a _lot_ of movement, making it more trouble than its worth to nixify Doom (or even trying to pull it every time I rebuild).

You'll find a popular effort to nixify Doom on https://github.com/vlaci/nix-doom-emacs, but I generally recommend against it. Emacs is a very stateful program with lots of moving part. `/nix`'s read-only-ness will cause issues without a lot of hackery that may cause their own problems. Once Doom is a little more mature I'll start thinking about making it more nixos/guix friendly, but we're at least a year away from that.

Anyhow, hope that helped!

**Comment by vandr0iy** [comment]
To follow on your answer up here: how does [that part](https://github.com/hlissner/dotfiles/blob/master/modules/editors/emacs.nix#L65) even work? If I attempt to uncomment it, this is what I get:
```
# nixos-rebuild switch --show-trace
error: The option `init' does not exist. Definition values:
       - In `/nix/store/ir0fjbffvd61nbg46j49w889dhav3nrx-source':
           {
             _type = "if";
             condition = true;
             content = {
               doomEmacs = {
           ...
```

**Comment by hlissner** [comment]
> how does [that part](https://github.com/hlissner/dotfiles/blob/master/modules/editors/emacs.nix#L65) even work?

It doesn't anymore, I'm afraid. I found my home-baked `init` option redundant with `system.userActivationScripts`. Here's how you'd adapt it:

```nix
system.userActivationScripts.installDoomEmacs = ''
  if [ -d $HOME/.config/emacs ]; then
     ${optionalString cfg.doom.fromSSH ''
        git clone git@github.com:hlissner/doom-emacs.git $HOME/.config/emacs
        git clone git@github.com:hlissner/doom-emacs-private.git $HOME/.config/doom
     ''}
     ${optionalString (cfg.doom.fromSSH == false) ''
        git clone https://github.com/hlissner/doom-emacs $HOME/.config/emacs
        git clone https://github.com/hlissner/doom-emacs-private $HOME/.config/doom
     ''}
  fi
'';
```

**Comment by vandr0iy** [comment]
Wow, that was _fast_ :exploding_head: Anyways, it works, thank you! 

P.S. You probably must've meant `if [ ! -d $HOME/.config/emacs ];` ?

**Comment by hlissner** [comment]
> P.S. You probably must've meant if [ ! -d $HOME/.config/emacs ]; ?

Whoops! Yes, you're correct. 

Glad I could help!
