### ISSUE TITLE
Dwm on nix

### ISSUE THREAD

**Issue by ashincoder** [hlissner/dotfiles#22]
Hey, 

I was wondering how could I use dwm on NixOs. Is it possible. Could u please share ur high wisdom to a peasant like me dark lord :bow:

**Comment by hlissner** [comment]
I've never used DWM, so I can't help much. [The nix wiki will have more answers than I can provide.](https://nixos.wiki/wiki/Dwm).

**Comment by ashincoder** [comment]
Thank you for showing. I am really scared to move to nixos. :fearful:
