### ISSUE TITLE
Suggestion: Update quickstart section in README

### ISSUE THREAD

**Issue by sdaros** [hlissner/dotfiles#23]
I just recently used the quick start instructions in the README to provision a new laptop, and I figured that it may be helpful for others (who aren't very familiar with the nix flakes approach) to clarify the quickstart section in the README. My suggestion would be something along the following lines:

4. switch to root user with `sudo su -`
5. nix-shell -p git nixFlakes
6. git clone https://github.com/hlissner/dotfiles /mnt/etc/nixos
7. Install NixOS: USER=<your_user_name_here> nixos-install --impure --root /mnt --flake /mnt/etc/nixos#XYZ, where XYZ is the host you want to install. Use #generic for a simple, universal config, or create a sub-directory in hosts/ for your device. See host/kuro for an example. If you added a folder in hosts/ don't forget to `git add hosts/new_folder_for_host` before running nixos-install.
Reboot!

I think just adding the `--impure` flag by default and reminding users to do a `git add host/new_folder_for_host` would be sufficient for new comers.

**Comment by halikular** [comment]
What is meant by this? `Install NixOS: USER=<your_user_name_here>` you write username before `nixos-install`?

**Comment by sdaros** [comment]
Yes that's correct. You enter your username as environment variable before the `nixos-install` command. 

The reason for this is that you are executing the `nixos-install` command as the root user (since you switched to the root user using `sudo su -` in step 4), but when setting up your system you usually want to also create a non-privileged, normal user as well and this only works when you set the environment variable `USER=your_user_name` (see https://github.com/hlissner/dotfiles/blob/master/modules/options.nix#L40-L41)

**Comment by hlissner** [comment]
I've updated the quickstart instructions in 809ee25 with your  suggestions and then some. Thanks for the help!
