### ISSUE TITLE
HEYYEYAAEYAAAEYAEYAA links do not match

### ISSUE THREAD

**Issue by ckiee** [hlissner/dotfiles#32]
### What did you expect to happen?

I refuse to use the fields so everything is going in here. The [link in the GH repository meta on the sidebar](https://youtu.be/ZZ5LpwO-An4) does not match [the link deep in the README](http://hemansings.com/). Which I think is weird. 

Something something consistency something something.

plsfix

### What actually happened?

These

### Describe your attempts to resolve the issue

fields

### Steps to reproduce

are

### Package commit

too

### System Information

restrictive.

**Comment by hlissner** [comment]
Disaster averted! Thanks for letting me know.
