### ISSUE TITLE
`countAttrs` doesn't work as expected 

### ISSUE THREAD

**Issue by archer-65** [hlissner/dotfiles#34]
### What did you expect to happen?

Here we are. My nix-fu isn't great, but maybe I found an issue with [this function](https://github.com/hlissner/dotfiles/blob/8fe1fbb6e7fc0d2f95fe75cdb9df7eb0595a0047/lib/attrs.nix#L24). I'm trying to use `countAttrs` as done in [this assertion](https://github.com/hlissner/dotfiles/blob/7d9f2dfb2f8db850c2be9abd30bdc034e8e8d263/modules/desktop/default.nix#L10).

I have a similar setup for my WMs, like that:
```nix
  cfgXorg = config.user-modules.desktop.xorg;
  cfgWayland = config.user-modules.desktop.wayland;

  ...
  
  {
    assertion = (countAttrs (n: v: n == "enable" && v) cfgXorg) < 2;
    message = "[Xorg] Can't have more than one WM/DE enable at a time.";
  }
  {
    assertion = (countAttrs (n: v: n == "enable" && v) cfgWayland) < 2;
    message = "[Wayland] Can't have more than one WM/DE enable at a time.";
  }
```

Something like this should print a backtrace! 
```nix
 user-modules.desktop.wayland = {
      enable = true;
      sway.enable = true;
      hyprland.enable = true;
 };
```

### What actually happened?

The evaluation continues, instead of printing the backtrace.

### Steps to reproduce

Enable at least two WMs (I'm using your functions for the same purpose) 

### Package commit

089f1a9da9018df9e5fc200c2d7bef70f4546026

**Comment by hlissner** [comment]
Sorry for only noticing this issue now, and you've probably already figured this out by now, but the problem is with the predicate function. Yours is only searching for a top-level `enabled` property, and not nested ones. They'd need to be rewritten to:

```nix
  {
    assertion = (countAttrs (_: v: v.enable or false) cfgXorg) < 2;
    message = "[Xorg] Can't have more than one WM/DE enable at a time.";
  }
  {
    assertion = (countAttrs (_: v: v.enable or false) cfgWayland) < 2;
    message = "[Wayland] Can't have more than one WM/DE enable at a time.";
  }
```

Hope that helps someone!
