### ISSUE TITLE
error: ipython-8.4.0 not supported for interpreter python3.7

### ISSUE THREAD

**Issue by Mastergamer433** [hlissner/dotfiles#36]
### What did you expect to happen?

When I do `sudo nixos-rebuild switch --flake .#kuro`, it should rebuild just fine.

### What actually happened?

When i do `sudo nixos-rebuild switch --flake .#kuro` it spits out an error about ipython, complaining about ipython 8.4.0 not supported for python3.7 interpreter. `error: ipython-8.4.0 not supported for interpreter python3.7`. The trace is so long it's very difficult to copy.

### Describe your attempts to resolve the issue

I have not tried anything.

### Steps to reproduce

I opened a terminal.
Typed these commands.
```
git clone git@github.com:hlissner/dotfiles
cd dotfiles
sudo nixos-rebuild switch --flake .#kuro
```
And then... error.

### Package commit

089f1a9da9018df9e5fc200c2d7bef70f4546026

### System Information

I use nixos 22.11 i think.

**Comment by hlissner** [comment]
Sorry for not seeing this issue sooner, but I don't think the issue is present anymore (the python ecosystem has seen many updates since this was opened, and I can't reproduce it), so I'll assume it was resolved upstream at some point along the way.
