### ISSUE TITLE
Absolute paths in `xdg.configFile`

### ISSUE THREAD

**Issue by musjj** [hlissner/dotfiles#38]
### What would you like to know?

How are you using absolute paths here?:

https://github.com/hlissner/dotfiles/blob/089f1a9da9018df9e5fc200c2d7bef70f4546026/modules/desktop/bspwm.nix#L51-L58

For me, I need to pass the absolute path string to `config.lib.file.mkOutOfStoreSymlink` first, or I would get this error:

```
error: access to absolute path '/absolute/path' is forbidden in pure eval mode (use '--impure' to override)
```

How are you working around this?

**Comment by hlissner** [comment]
By running all nix commands (where possible) in impure mode ([for example](https://github.com/hlissner/dotfiles/blob/master/bin/hey#L75)).

**Comment by musjj** [comment]
I see, thanks for answering!
