### ISSUE TITLE
Fail to update all topics with `zsh depoly -a`

### ISSUE THREAD

**Issue by kids300** [hlissner/dotfiles#4]
When I was executing `zsh depoly -a`, it showed the error message: `[FAIL] topic/topic topic/topic topic/topic doesn't exist!`at `topic-init:4>`, where `[[ ! -d 'dev/java dev/python editor/emacs misc/docker misc/weechat shell/mu shell/zsh' ]]` at line 3 failed. 

I use 
```
function topic-init {
  IN=(${=@})
  for topic in $@; do ...
```
to split string into list, and it works for now.

**Comment by hlissner** [comment]
Ah! This issue slipped past me completely! Good catch. I've updated the deploy script to fix this issue in 291d647. Thanks for letting me know!
