### ISSUE TITLE
NixOS Wiki move

### ISSUE THREAD

**Issue by Denperidge** [hlissner/dotfiles#40]
### What would you like to know?

Hi! A quick headsup that an RFC is up at https://github.com/NixOS/foundation/issues/113 to phase out `nixos.wiki` for `wiki.nixos.org`. If you still prefer linking to nixos.wiki that is totally valid, but thought I'd bring it up! 😌

**Comment by hlissner** [comment]
I've corrected the link. Thanks for letting me know!
