### ISSUE TITLE
Can't access default lib modules after extending nixpkgs.lib

### ISSUE THREAD

**Issue by shadowrylander** [hlissner/dotfiles#8]
Hello!

I can't seem to access the default lib modules after extending `nixpkgs.lib`; when trying to access `mkDefault`, for example, the error states that the attribute doesn't exist.

Here are my [`flake.nix`](https://www.github.com/shadowrylander/shadowrylander/tree/system/etc%2Fnixos%2Fflake.nix) and my [`lib/default.nix`](https://www.github.com/shadowrylander/shadowrylander/tree/system/etc%2Fnixos%2Fshared%2Fglobal%2Flib%2Fdefault.nix).

Thank you kindly for the help!

Update: [here's](https://www.reddit.com/r/NixOS/comments/jjhw44/review_lib_module_extension/?utm_medium=android_app&utm_source=share) a reddit post I created as well.

**Comment by shadowrylander** [comment]
Actually, I might've fixed that; now I need to know why using the extended lib with `imports` (before `config`) is throwing errors that the names of my attribute sets for my paths in [`path.nix`](https://github.com/shadowrylander/shadowrylander/blob/system/etc/nixos/shared/global/lib/paths.nix) are not options!

**Comment by shadowrylander** [comment]
Pinging @hlissner; sorry! I'm just really, really stuck on this next bit!

**Comment by shadowrylander** [comment]
Well that's strange; I somehow fixed the next error by not using the `lib.my.paths` in my modules list...

**Comment by shadowrylander** [comment]
And it seems I've come back full circle; some modules cannot seem to access certain variables in the `lib` module, whether built-in, such as `mkForce`, or my own.

**Comment by shadowrylander** [comment]
Actually, it seems like I can't access anything from the extended module; the attributes are either seen as missing, or are confused for options by the Nix interpreter.

**Comment by shadowrylander** [comment]
It would appear as though usage of your lib extension fails with the same errors as well.

**Comment by hlissner** [comment]
Sorry for only noticing this issue now, but I imagine you must've gotten around this by this point. I've since restructured my local libs to further disambiguate them from nixpkgs.lib, so I'll assume it's been resolved at some point along the way. Thanks for bringing it to my attention, in any case!
